### ISSUE TITLE
Page is refreshed when the enter key is clicked

### ISSUE THREAD

**Issue by tolgaaaltas** [therealsujitk/flarum-ext-gifs#2]
The page refreshes instead of searching when the enter key is clicked while the cursor is in the input field.

**Comment by therealsujitk** [comment]
Thanks for letting me know, I'll try and fix the second issue as soon as possible.

> The "Search" text translation has been corrected in **v1.4.5**.

**Comment by therealsujitk** [comment]
@tolgaaaltas Fixed this issue in **v1.4.7**
