### ISSUE TITLE
JS compiled for development mode and not prod

### ISSUE THREAD

**Issue by Ralkage** [therealsujitk/flarum-ext-gifs#8]
Hey there 👋

Just recently ran Clark's migrate to Flarum scanner on my forum and from the results, it looks as if the JS for your extension is still compiled for dev mode.

![image](https://user-images.githubusercontent.com/2059356/94327296-fda71c80-ff77-11ea-9f8b-3a09c6326afa.png)

Would you be able to fix that? I really like using this extension :)

**Comment by therealsujitk** [comment]
I'm really happy you like my extension 😇. I'm a little busy with exams right now, I hope you don't mind waiting a bit. I will be able to fix this tomorrow night or on monday at the latest.

**Comment by therealsujitk** [comment]
@Ralkage the issue should be fixed in **v1.4.9**. Thanks for bringing this to my attention!
